/**
 * Author: Professor Krasso
 * Date: 7 August 2024
 * File: app.js
 * Description: Application setup. Autogenerated using Express generator.
 */

// require statements
const express = require("express");
const cookieParser = require("cookie-parser");
const logger = require("morgan");
const { notFoundHandler, errorHandler } = require("./error-handler");
const listInventoryRoutes = require("./routes/list_inventory");
const createInventoryRoutes = require("./routes/create_inventory");
const readInventoryRoutes = require("./routes/read_inventory");

// Importing the index router
const indexRouter = require("./routes/index");

// Variable declaration for the express app
let app = express();

const mongoose = require("mongoose");
require("dotenv").config();

// Connect to MongoDB Atlas
mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("Connected to MongoDB Atlas"))
  .catch((err) => console.error("MongoDB connection error:", err));

// CORS configuration
app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, DELETE, OPTIONS"
  );
  res.setHeader(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );
  next();
});

// Express app configuration
app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Routing configuration
app.use("/api", indexRouter);
app.use("/api/inventory", listInventoryRoutes);  // GET /api/inventory
app.use("/api/inventory", createInventoryRoutes); // POST /api/inventory
app.use("/api/inventory", readInventoryRoutes);   // GET /api/inventory/:id

// Use the error handling middleware
app.use(notFoundHandler);
app.use(errorHandler);

// Export the app
module.exports = app;
